import Navbar from "@/components/layout/Navbar";
import Hero from "@/components/sections/Hero";
import Testmonials from "@/components/sections/Testmonials";
import { Archivo } from "@next/font/google";
import Head from "next/head";

const archivo = Archivo({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${archivo.className}`}>
        <Navbar />
        <Hero />
        <Testmonials />
      </main>
    </>
  );
}
