import Navbar from "@/components/layout/Navbar";
import Hero from "@/components/sections/Hero";
import CenterContent from "@/components/wrappers/CenterContent";
import { Roboto } from "@next/font/google";
import Head from "next/head";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${roboto.className} font-sans bg-[#f3efec]`}>
        <CenterContent>
          <Navbar />
          <Hero />
        </CenterContent>
      </main>
    </>
  );
}
